### ISSUE TITLE
Transfer Allocations from README to Seperate Files

### ISSUE THREAD

**Issue by mikenabhan** [router-city/router-city#1]
How would y'all feel about moving the allocations from README to seperate files so that the readme is able to stay a bit more clean?

If you like it, I will take charge on this.

**Comment by Famicoman** [comment]
Would you purpose just moving the tables to separate files? I think there is a need to keep the justifications and whatnot for the blocks chosen to be on the README, but I think the actual user allocations can be moved to separate files, especially as they grow. It may be good to still reiterate what block to allocate from on these separate pages to wayward users don't have to flip back.

Thoughts?

**Comment by mikenabhan** [comment]
That is sort of what I am thinking.   An allocation directory with a file each for ASN, IPV4, IPV6.  I'll branch it and send a pull request.

**Comment by mikenabhan** [comment]
Pull request here: 

https://github.com/router-city/router-city/pull/2
